### ISSUE TITLE
Negative modifier allows limitless quarz upgrade on swords

### ISSUE THREAD

**Issue by ruyanve** [SlimeKnights/IguanaTweaksTConstruct#101]
Sorry if this is a duplicate, I checked the closed issues and changelog but couldn't find anything related... maybe I'm blind.

Forge 1291
TConstruct-1.7.10-1.8.2a
IguanaTinkerTweaks-1.7.10-2.1.2

Modlist: http://pastebin.com/tsCaNMnP

When upgrading a sword (tested on cleaver only so far) with quarz to level 1 (72), then replacing a part (only tested with higher tier part), you'll end up with a quarz modifier of 72/86 and the ability to endlessly keep adding quarz.

You'll end up with something like this:

![iguana_ticon_2](https://cloud.githubusercontent.com/assets/7439516/6359565/75679d14-bc74-11e4-938d-561953ab9a82.png)
![iguana_ticon_1](https://cloud.githubusercontent.com/assets/7439516/6359572/7b827d36-bc74-11e4-9e8f-c4c4d2018312.png)

**Comment by bonii-xx** [comment]
Yup, already fixed

**Comment by ruyanve** [comment]
Dang it! I AM blind then! Sorry!!

**Comment by bonii-xx** [comment]
But you're the first to find the actual cause ;P
