### ISSUE TITLE
Repairing chisel in 2x2 crafting grid duplicates the chisel.

### ISSUE THREAD

**Issue by codewarrior0** [SlimeKnights/IguanaTweaksTConstruct#104]
Probably because the chisel returns itself to inventory when using chisel recipes. Not sure how to fix it, only workaround is to repair in tool stations.

**Comment by bonii-xx** [comment]
Can't be fixed because vanilla MC

**Comment by codewarrior0** [comment]
Thought so. At least, could you block chisels from being repaired that way?

**Comment by bonii-xx** [comment]
I suppose I could. I just don't see it as a big issue because.. it's only a chisel. ;o

**Comment by squeek502** [comment]
If I understand the problem correctly, you can actually fix this easily using Forge events. Use PlayerEvent.ItemCraftedEvent and check for the chisel as the output, and if it is, decrease the stacksize of the input chisel or set it to null.

Example: https://github.com/squeek502/VeganOption/blob/master/java/squeek/veganoption/content/modifiers/CraftingModifier.java#L55-L93

**Comment by bonii-xx** [comment]
Oh, good idea. Only solution I found was the crafting handler, but there I can't do that because it'd reduce it before it's pulled out.

**Comment by bonii-xx** [comment]
Works like a charm squeek <3
