### ISSUE TITLE
tool station bug

### ISSUE THREAD

**Issue by aldra2012** [SlimeKnights/IguanaTweaksTConstruct#105]
with the latest dev build i noticed when you repair your tool and/or changing tool parts in the tool station the parts stay but still get applied to the tool. not sure if its iguana tweaks tcon or tcon itself

**Comment by bonii-xx** [comment]
That was a bug in Tcon.

**Comment by aldra2012** [comment]
my apology i noticed it has been fixed in the latest build so thank you and i shall resume testing it all out
