### ISSUE TITLE
Level 4 Harvest Level Not Overriden

### ISSUE THREAD

**Issue by johnnyzcake** [SlimeKnights/IguanaTweaksTConstruct#108]
In HarvestLevelNamesOverride.cfg I used the following format:

HarvestLevelNames {
	S:Level0=Stone
	S:Level1=Copper
	S:Level2=Bronze
	S:Level3=Iron
	S:Level4=Diamond
	S:Level5=Obsidian
	S:Level6=Ardite
	S:Level7=Cobalt
	S:Level8=Adamantine
	S:Level9=Atlarus
}

All levels were changed to the corresponding text, with the exception of level 4, which remained as REDSTONE, which normally won't be an issue but in my modpack, Redstone is actually level 3 or IRON level.

**Comment by bonii-xx** [comment]
Only tinker-materials are supported. The comment does not really explain this properly.
It'll be somewhat remedied by 9d8a10230788591b4028abfece57d56385abdd28
