### ISSUE TITLE
Copper not mineable with flint

### ISSUE THREAD

**Issue by bobsoppe** [SlimeKnights/IguanaTweaksTConstruct#109]
Like shown in the two images below, it is not possible for me to mine copper ore.
I'm not really sure if it is a config I missed, some mod is messing it up or something else.
Ores used:
- All from Thermal Foundation
- Aluminium from Tinkers' Construct
- Apetite from Forestry
- All Thaumcraft ores
- All Project: Red ores
- All Applied Energistics 2 ores
- Big Reactors ore
- Dense Ores dense ores ;)

Copper ore with WAILA:
![screen shot 2015-03-05 at 19 51 23](https://cloud.githubusercontent.com/assets/6442837/6512024/29c86af6-c371-11e4-954f-238ff8ef95f5.png)

Flint tool used:
![screen shot 2015-03-05 at 19 51 29](https://cloud.githubusercontent.com/assets/6442837/6512026/2d53139c-c371-11e4-9b25-d4bf8e223bdc.png)

Modlist:
http://pastebin.com/SwJ79nYU

Configs of Iguana Tinker Tweaks are default.

**Comment by bonii-xx** [comment]
Boost your pick.
