### ISSUE TITLE
AutoSmelt and Repair Auto Levelup Modifier Config

### ISSUE THREAD

**Issue by AladinsjustSayian** [SlimeKnights/IguanaTweaksTConstruct#110]
The allowAutoSmelt and allowRepair boolean config for random leveling modifier is not turning off when it is "false" in the config file. I am using Version 2.1.2. I get these modifiers on my sword and bow, but not anything else.

**Comment by bonii-xx** [comment]
Disable completelyRandomBonuses.

**Comment by AladinsjustSayian** [comment]
It is disabled, It respects all other config settings, but autosmelt and repair are still applied at random.

**Comment by bonii-xx** [comment]
It is impossible to get a modifier that is disabled or not-useful with useful bonuses enabled. Your configs are probably incorrect.
