### ISSUE TITLE
[question] reguarding sword modifiers

### ISSUE THREAD

**Issue by kurokuno** [SlimeKnights/IguanaTweaksTConstruct#112]
was just wondering why it seems swords never get the attack modifier randomly when leveling yet every other T-con weapon does ? even if i set the sword to get a modifier every level and cap it to 99 then just spam level up commands it never gets attack

was just wondering if this was intended or maybe a tiny oversight

**Comment by bonii-xx** [comment]
Bad RNG in an artificial situation.

**Comment by bonii-xx** [comment]
I just remembered that there used to be a bug with the attack modifier from a certain tinkers version on. Might also be that. Anyway it should be fixed in the next version.
