### ISSUE TITLE
ITT overwrites TE tooltips and names

### ISSUE THREAD

**Issue by Adaptivity** [SlimeKnights/IguanaTweaksTConstruct#115]
[With ITT installed](http://i.imgur.com/6kLjCxC.jpg)
[Without ITT installed](http://i.imgur.com/7bUloP2.jpg)
As I said previously, it might worth to remove all TF names from Tcon .lang files since [they are already in](https://github.com/CoFH/ThermalFoundation/blob/master/src/main/resources/assets/thermalfoundation/lang/en_US.lang#L296) but it's seems that ITT always check Tcon .lang file and it can't read TF .lang file. Might related to: #82
Confirmed affected versions:
ITT: 2.1.4, DEV 134, 136
Tcon: 1.8.4a, 1.8.4, 1.8.3b, 1.8.2a, 1.8.2
MFR: 2.8.1B1-108 and previous
TF: 1.0.0-81 and previous
TE: 4.0.1-182 and previous

**Comment by Adaptivity** [comment]
Any idea how to fix this? I want to see TE tooltips :D

**Comment by bonii-xx** [comment]
I forgot what exactly is used to determine the position where the tooltips are inserted in the tooltip list (every line is an entry), but i think the mod that adds the "TConstruct Weaponry" at the top is at fault.

**Comment by Adaptivity** [comment]
Wait. ITT ovewrites not only tooltip, it's overwrites name of tool too. ITT somehow changes first unlocalized word of tool. Let me show and now without TConstruct Weaponry tooltip:
ITT installed: http://i.imgur.com/qzee0YP.jpg
Without ITT: http://i.imgur.com/4bFWa1v.jpg
Both tested with the same mods and Forge.

**Comment by Adaptivity** [comment]
@bonii-xx you've checked that?

**Comment by Adaptivity** [comment]
MFR-Tcon tools affected too. But they completely have no names since they are not in Tcon .lang file.

**Comment by bonii-xx** [comment]
What versions are you using?

**Comment by Adaptivity** [comment]
All latest versions, Forge 1388.

**Comment by Adaptivity** [comment]
And here MFR missing names: http://i.imgur.com/w2jilq9.jpg http://i.imgur.com/3Ojq9GK.jpg tooltips are removed too. Removing ITT does fixes the problem.

**Comment by bonii-xx** [comment]
Derp. I thought it was a problem with the overwrite module. Turns out I never changed it in the original harvestlevel-changes stuff.

**Comment by Adaptivity** [comment]
MFR names now working as intended. But TF material names now unlocalized and tooltip is missing at all. Maybe TF problem? But without ITT everything works fine.

**Comment by Adaptivity** [comment]
Apparently, I forgot that I messed up TF .lang files. I redownloaded TF and now everything working. Thank you for the fix.
