### ISSUE TITLE
Item Stats

### ISSUE THREAD

**Issue by LawDawg0607** [SlimeKnights/IguanaTweaksTConstruct#116]
How do we fix the item stats problem in 2.1.2.  We have tried "The game will try to update your tools if they have incorrect stats. If the tooltip tells you it's incorrect, simply put it into any crafting window and pull out the (hopefully) fixed tool."   This fix is not working for us.  It will not allow the tool to be pulled out.  Is there a config we need to change to allow this to work properly or do we just need to upgrade the version or stop using the mod until it can be fixed?

**Comment by bonii-xx** [comment]
You can always pull it out unless your server and client configs are out of sync.
Also try updating.
