### ISSUE TITLE
[Bug] Clay Fired bucket doesn't get destroyed

### ISSUE THREAD

**Issue by Biofusionz** [SlimeKnights/IguanaTweaksTConstruct#117]
Using a clay bucket with lava in on a magmatic dynamo from TE doesn't destroy the bucket

**Comment by bonii-xx** [comment]
Can't confirm, bucket is getting destroyed accordingly.

**Comment by Biofusionz** [comment]
What versions are you using?
I'm using the latest of
CoFHCore
CoFHLib
IguanaTinkerTweaks
Mantle
TConstruct
ThermalExpansion
ThermalFoundation

I've tested it with clean configs too...
There's definitely something making this happen

**Comment by Adaptivity** [comment]
@bonii-xx can confirm this. This still happens on latest versions... I've also saw reports about it somewhere else... reopen?

**Comment by bonii-xx** [comment]
To elaborate, that seems to happen because TE seems to have changed how their tanks do stuff. The callbacks are not even getting called. Has to be fixed on their side.

**Comment by Biofusionz** [comment]
@KingLemming

**Comment by KingLemming** [comment]
What callbacks are you talking about boni?

**Comment by bonii-xx** [comment]
EntityInteractEvent (not needed for this though) and OnItemRightClick (https://github.com/SlimeKnights/IguanaTweaksTConstruct/blob/master/src/main/java/iguanaman/iguanatweakstconstruct/claybuckets/items/ClayBucket.java#L44). The tanks handle the liquid stuff themselves, so the bucket actually has no say in it at all. I'm surprised the clay buckets work correctly without it.

**Comment by KingLemming** [comment]
onItemRightClick() will only fire when you don't interact with a block, it's the last thing in the logic chain. That's not us doing it though, that's Minecraft.
