### ISSUE TITLE
Iguana Modifier crash

### ISSUE THREAD

**Issue by IAA-ShRaPNeL** [SlimeKnights/IguanaTweaksTConstruct#118]
Upon receiving a reward modifier, this case being Haste, a crash occurs. Does not happen all the time, not sure what caused it this time. 

Edit: It appears that after a certain amount of Haste being applied, any subsequent haste causes a crash upon reward. 

Log: http://pastebin.com/3ejCqJ3Y

**Comment by bonii-xx** [comment]
Update.

**Comment by IAA-ShRaPNeL** [comment]
Yep. Thanks.
