### ISSUE TITLE
disableStoneTools config setting doesn't seem to have any effect

### ISSUE THREAD

**Issue by merdink** [SlimeKnights/IguanaTweaksTConstruct#120]
Version 2.1.3.130

> Stone Tools can only be used to create casts, but no tools [default: true]
>    B:disableStoneTools=true

I have tried setting it to false also (just in case it was backwards), which had no effect. I am still able to make a tinker tool with stone parts. I never see the red text telling me the stone parts are only for casting.

**Comment by bonii-xx** [comment]
Then it's either not true on the server you're using, or you got errors in your log.

**Comment by merdink** [comment]
Never mind, I guess I should have tested it alone. Setting works fine when its just Tinkers and Tinkers Tweaks. I guess its either Jaded's configs or one of the other mods in the Magic Farm 3 pack that causes the issue.
