### ISSUE TITLE
Error Thrown on Server Start

### ISSUE THREAD

**Issue by Cuppycake** [SlimeKnights/IguanaTweaksTConstruct#121]
Server goes through FML Confirm, begins to load normally and then tosses this error twice and ends the server in an Incorrect State.

http://pastebin.com/9qXJbk5C

**Comment by bonii-xx** [comment]
Full log?

**Comment by Cuppycake** [comment]
http://mechandmagic.com/fml-server-latest.log

Sorry I could not fit it on any other pasting service so I linked it off my server as a txt file. 
If you feel uncomfortable with that I understand and will try to figure out another way to get it to you.

**Comment by bonii-xx** [comment]
That stacktrace makes zero sense. There is no code in forge that calls those functions in those places. o_O

**Comment by Cuppycake** [comment]
Could this have anything to do with tools having RF capacitors on them?

**Comment by bonii-xx** [comment]
Nope. It's probably some other mod you got there.

**Comment by Cuppycake** [comment]
Alright well I guess I'll push my update without your newest version then do the pain staking one by one until I find the bugger haha.  Thanks.

**Comment by Xew** [comment]
I was having the same issue but it was Enhanced Server Moderation 0.9.9.68 that was causing the issue.

**Comment by bonii-xx** [comment]
Thanks for finding the offender @Xew
