### ISSUE TITLE
Vanilla tools don't respect server config

### ISSUE THREAD

**Issue by 61352151511** [SlimeKnights/IguanaTweaksTConstruct#122]
I changed the config to not disable vanilla tool effectiveness and yet a diamond pickaxe can still not mine stone, either the harvest level of stone was changed a lot, or the tools don't respect the config option.

**Comment by bonii-xx** [comment]
Sounds like you did something wrong or changed the wrong config option.

**Comment by 61352151511** [comment]
In the logs there is

[14:29:58] [Server thread/DEBUG] [IguanaTweaksTConstruct/IguanaTweaksTConstruct]: Changed Harvest Level for pickaxe of item.pickaxeDiamond from 3 to 5

I'm chopping away at stone with a diamond pickaxe and it's not breaking. Here's my config file:

http://puu.sh/gQmHf.txt

**Comment by 61352151511** [comment]
Fixed it, don't know how, I just cleared S:mods list

**Comment by 61352151511** [comment]
It's when there is a mismatch between the client and the server, it seems the client is determining whether or not the blocks can be mined instead of the server.

**Comment by sapid** [comment]
Confirmed. `B:disableStoneTools=false` was set on the server, but the client ignored it until I changed it to false client-side as well. I was tearing my hair out trying to find a mod incompatibility. Thanks for the tip, 61352151511.

**Comment by bonii-xx** [comment]
Not sure what'd make you think that configs don't have to be synced between client and server. Configs should always match.

**Comment by 61352151511** [comment]
I know configs SHOULD match but sometimes they don't and shouldn't have to. If it's something like this it should be determined by the server and not the client. I've got my modpack set up to have no configs in it and just let the client generate them all upon start up. Some of the configs I have to include (like this one) because of things that shouldn't matter but do.

Say you had two servers with the same mods but the configs for all the mods are highly different between the two servers. You shouldn't need two instances of the modpack or to switch the config folders every time you want to switch servers. When the player joins a server tell the player "Hey, vanilla tools aren't allowed here" and then set the config value, when they leave, set it back to whatever they have it set to.

**Comment by bonii-xx** [comment]
Welcome to modded minecraft. :)

**Comment by 61352151511** [comment]
No need to say "welcome" I've been playing modded minecraft for at least two years, I've been making mods myself for at least half a year. I know exactly how mods work. I know it's possible to make this "Disable vanilla tools" a server sided config. I'm not sure why you don't feel like taking a look into doing it, it would be really simple to fix.

**Comment by bonii-xx** [comment]
It simply uses the events to prevent break process. They shoudl be called server side actually.
However, the PR button is in the top right. :p
