### ISSUE TITLE
"B:pickaxeBoostRequired" Does nothing when changed to false

### ISSUE THREAD

**Issue by Razorskills** [SlimeKnights/IguanaTweaksTConstruct#123]
In the pickleveling section of the main config

"B:pickaxeBoostRequired" Does nothing when changed to false.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2176855-iguanas-tinker-tweaks?comment=597

-----------------
On a side note, Is it possible to have:
```
" info" {
    # Fills this file with the default values, not altering changed values.
    B:fillWithDefault=true

    # Removes all entries that correspond to the default values. Will likely fail with some materials because floats are derp.
    B:removeDefaultValues=false
}
```
in the BlockOverridde.cfg?

**Comment by bonii-xx** [comment]
Works perfectly fine for me.

The fill stuff doesn't make too much sense because of the oredict. For everything else there's the BlockDefaults.cfg

**Comment by Razorskills** [comment]
hmm perhaps we are using the config incorrectly, if I switch the config to false, either all the ores should bump back down to the normal mining level, or the pickaxes mining level should bump up right?

after this config, stone should be able to mine coal, or even tin / copper.

but here is another person who tested the config here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2176855-iguanas-tinker-tweaks?comment=598

he also found the config to do nothing.

**Comment by bonii-xx** [comment]
...no, that's not what this config does. As the name and comment says, it removes the requirement to level your pick. You want to disable the harveststuff module.
