### ISSUE TITLE
Diminishing repair effect

### ISSUE THREAD

**Issue by Methes** [SlimeKnights/IguanaTweaksTConstruct#129]
In MC 1.6.4 there used to be this option:
I:repairScalingModifier=5
B:repairCostScaling=false

Now it's missing and every repair adds less to the tool durability, rendering it useless after using it for a long time.
Could this function be added back, please?

**Comment by bonii-xx** [comment]
Vanilla TCon already does that, this just allowed to modify the rate of it. If you want actual limited repairs, use the config for that.

**Comment by Methes** [comment]
Exactly. And I'd like to disable the diminished repairs like I was able to before.

**Comment by bonii-xx** [comment]
..unless you set a maximum amount of times it can be repaired, as i said above.
