### ISSUE TITLE
diamondRequired still is breaking tool data when set to false.

### ISSUE THREAD

**Issue by Claycorp** [SlimeKnights/IguanaTweaksTConstruct#131]
#64 is not fixed.

If you set B:diamondRequired=false it removes the ability to add diamonds/emeralds and if you get them via Auto-Level it breaks to the tool data and if you place it in a crafting window it will break the mining level. It often is boosted to cobalt mining level after trying the 'recommended' fix.

I would like to keep the durability changes without the mining level changes. Perhaps splitting the option into two one to disable mining level changes and then applying it to bronze to get diamond level?

**Comment by bonii-xx** [comment]
So.. you want the diamond/emerald config option in vanilla tinkers?

**Comment by Claycorp** [comment]
No. I personally don't want it but because you need the bronze+diamond to get obsidian. I thought that it might have been simpler to just change the config option to disable gem mining level changes and then another option to disable/enable the Bronze+diamond replacement to steel.

**Comment by Razorskills** [comment]
I am also interested in this ^

**Comment by bonii-xx** [comment]
..you can always use steel no matter what the config is?

**Comment by Claycorp** [comment]
Yes. You can use steel but if you want to force people to use the tier system bronze > steel > alumite. You don't want the bronze+diamond harvest level change but if you change it it removes the harvest level edit and gem modifiers.

Reasoning:

It is under the "harvestleveltweaks" part of the config.
Most would assume this edits harvest level related configs.

The description for the option is this
"Changes the Diamond and Emerald modifier: Apply it to a bronze level tool to obtain diamond level. Required unless you have steel or similar. [default: true]"
Again this implies that it is only editing the Bronze harvest level change. As Diamonds and emeralds already don't increase harvest levels on any other tool so this being true must do those things.

So someone reading this understand this:
* True = Fully leveled bronze + diamond = Obsidian harvest level and diamonds or emeralds don't boost any harvest levels.
* False = Fully leveled bronze + diamond = No harvest level change and diamonds or emeralds boost harvest levels.

This is what it currently will do:
* True = Enables fully leveled bronze + diamond = Obsidian harvest level and allows for Diamond + Emerald modifiers. This allows for durability buffs from diamonds and emeralds on tools.
* False = Disables fully leveled bronze + diamond = Obsidian harvest level and removes the ability to add Diamond + Emerald modifiers completely. Including the durability buffs they give.

What I suggest to change it to is:
"gemDurability = true/false" This allows or disallows diamonds or emeralds from editing durability.
"bronzeGemHarvest = true/false" This allows or disallows diamonds or emeralds from boosting the harvest level of bronze.
OPTIONAL: "gemHarvest = true/false" Allows for just harvest level changes for diamond and emerald.

**Comment by bonii-xx** [comment]
That is incorrect. Diamond/Emerald ALWAYS give their durability and can always be obtained. The config option does not have any affect on that.

**Comment by Claycorp** [comment]
Fresh install of Tinkers, Mantel and Tinkers tweaks nothing else.  

http://i.imgur.com/LaMIQb6.png Works fine. No config changes.

http://i.imgur.com/0Op2PdP.png Breaks tool. Config change was B:diamondRequired=false and the removal of all other random modifiers so I got it right away. Same tool as before.


I was wrong about the option disabling the diamond/emerald modifiers. (Must not of had a modifier when it happened or it wasn't working because the tool was messed up.)
Still the issue is that the tool data breaks if diamond or emerald is randomly applied when that option is set to false.  

I still think the options would be nice to have. Thats up to you.

**Comment by bonii-xx** [comment]
What version of ITT are you using? Also the message has no actual impact on the functionality, and there are a *ton* of edge cases. Might be one of those, but pretty much all of them should be fixed in the last version.

**Comment by Claycorp** [comment]
V2.1.4 And this is a major issue because if you follow the tip to put it in a crafting window it sets the harvest level to cobalt. Even on flint.

**Comment by bonii-xx** [comment]
If you take a new flint pick, add diamond/emerald, what harvest level does it have? If it's incorrect, what does the result get? Of the new pick.

**Comment by Claycorp** [comment]
Adding the diamond manually it is fine. When it gets it randomly it breaks.

**Comment by bonii-xx** [comment]
Then something else messes with it. It doesn't matter if it's added manually or by levelup, it's exactly the same thing.

**Comment by Claycorp** [comment]
If it was working this issue wouldn't exist.

**Comment by bonii-xx** [comment]
Well, you also haven't given me all the infos you could give me. ;P

**Comment by Claycorp** [comment]
I don't know what else to give? Leveling the tool with that config false = broken tool. No logs are created that I found.
If its true its fine.

This is still the case with just tinkers, mantel and tinkers tweaks so its not an interaction of mods doing it.

I have nothing else to give.

**Comment by bonii-xx** [comment]
I believe I found the culprit. Another edge case. However you might still want to disable the harvest-levels given by diamond/emerald in the tinkers config.

**Comment by Claycorp** [comment]
PRASE ALL THE TOOL LORDS!

I will do that. (The fact that I clicked this tab and you responded was creepy)

**Comment by bonii-xx** [comment]
(Don't look behind)
