### ISSUE TITLE
Mining level boost modifier hardcoded

### ISSUE THREAD

**Issue by Adaptivity** [SlimeKnights/IguanaTweaksTConstruct#14]
Move it in .lang file.

**Comment by Adaptivity** [comment]
So, is there are anyway to rewrite modifiers so they can use localization? Tried to use StatCollector but yeah it doesn't work :smile:

**Comment by bonii-xx** [comment]
The problem is that those strings are sometimes also used as data-values in NBT. Separating those 2 applications would require some changes to the modifiers, which might cause incompatibilities, which is why I'm likely gonna leave them as is. ;)

**Comment by Adaptivity** [comment]
Might cause incompatibilities? Can we just try to localize them? In experimental branch for example.
