### ISSUE TITLE
Incorrect Tool Data On Multiplayer (RR3)

### ISSUE THREAD

**Issue by cybeel** [SlimeKnights/IguanaTweaksTConstruct#140]
So I decided to make a RR3 server for a few friends of mine to play on together. At first we couldn't disable the "nerf vanilla tools" option in the config files of IguanaTweaks so we decided we would get a blast furnace up and running before we start using Iguana, so we disabled the mod completely. Now, when we re-enable the mod, ALL the TiC tools get the "this tool has incorrect data" tooltip and placing it in the crafting grid and ttrying to take it out doesn't work; the tool puts itself back in the crafting grid. I know that this is probably our fault for disabling the Iguana mod completely but is there a way around this?

**Comment by bonii-xx** [comment]
Sync client and server configs.
