### ISSUE TITLE
[Request] Ability to add items to be smelted into a type of fluid

### ISSUE THREAD

**Issue by Razorskills** [SlimeKnights/IguanaTweaksTConstruct#142]
Basically all the railcraft steel tools, and armor do not work in the smeltery. It would be very nice to have support added for it(although that sounds more like something for ExtraTiC I will put in a ticket there for that)

or a module that a pack author could do it themselves. perhaps you could specify an item, and what type of liquid it smelts into, how much you get from one item, and maybe how long it takes to smelt it?

I hope you also think this would be useful. But if not. just close the ticket.

**Comment by bonii-xx** [comment]
ITT is not the place for this. Get the mod author to support it or use Minetweaker.
