### ISSUE TITLE
Extra Utilities Diamond Spikes don't Kill Mobs when Vanilla swords are Disabled

### ISSUE THREAD

**Issue by shartte** [SlimeKnights/IguanaTweaksTConstruct#143]
I am not quite sure where to file this bug. When vanilla swords are disabled in iguana tweaks (i.e. like in Agrarian Skies 2), then the extra utilites diamond spikes only damage enemies up to 1/2 a heart and never kill them. Is it possible to exempt the EU spikes from the vanilla sword nerfs? (I don't know how it's implemented, but I am guessing a fake vanilla sword is used for damaging the mobs)

**Comment by bonii-xx** [comment]
Nope. Also if I remember correctly tema fixed that and/or left it in that one kind of spikes keeps that behaviour intentionally. Try updating your XU.
