### ISSUE TITLE
Incompatibility with Erebus mod + Extra TiC

### ISSUE THREAD

**Issue by caiofaustino** [SlimeKnights/IguanaTweaksTConstruct#144]
I left a similar issue at their github, basically when I install Erebus, the mechanic that disables the other tools stops working.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2244153-0-2b-the-erebus-latest-release-is-out-block-o
http://www.curse.com/mc-mods/minecraft/220698-the-erebus

Its probably something on their side, but if you could take a look and maybe help them out that would be awesome.

Thanks in advance.

**Comment by Drakray** [comment]
Erebus also disable the "part reuse" function

**Comment by Galvanize** [comment]
So further testing showed that the bug actually only happens with both Erebus and Extra TiC installed.
I talked to Glassmaker and he pointed out a couple erros on my log.
http://paste.ubuntu.com/11693711/

On line 5893, InvocationTargetException.
