### ISSUE TITLE
Clay Bucket API

### ISSUE THREAD

**Issue by TinkerWorX** [SlimeKnights/IguanaTweaksTConstruct#147]
Would it be possible to get a clay bucket API? I would like to add support for Sludge, Sewage, and other liquids from MineFactory Reloaded. Alternatively, the support could be native, although I'm not sure how I'd contribute this to the source.

**Comment by bonii-xx** [comment]
The claybuckets are hardcoded and completely separate from everything else. Clay buckets for other materials could be added by any mod - they are required to be separate items.
You can find everything in the claybucket package.

**Comment by TinkerWorX** [comment]
Alright, so if I'm understanding this right, I just make a FillBucketEvent handler, check for the fired clay bucket and then implement the behavior of a bucket.

**Comment by LegendLength** [comment]
Would you consider adding support for Ex Nihilo witch water and clay buckets?

**Comment by TinkerWorX** [comment]
I have made a small mod which adds support for various fluids, mainly forestry and MFR. It needs a custom build of Iguana Tweaks though, due to a bug In the clay bucket code. I could add Ex Nihilo and put it up somewhere if you're interested?

**Comment by LegendLength** [comment]
That would be great thanks.

**Comment by bonii-xx** [comment]
Is it a general fix? If it's safe and you PR it you can use a jenkins build for it.

**Comment by TinkerWorX** [comment]
Here's the mod which adds support for more liquids. Built against forge 1558. https://github.com/TinkerWorX/IguanaTweaksMoBuckets/tree/master
It requires the latest commits to IgTweaks, which you'll either have to build yourself or as boni nicely about.

**Comment by bonii-xx** [comment]
Actually, we have a Jenkins for that: https://dvs1.progwml6.com/jenkins/job/IguanaTConTweaks-1.7.10/lastSuccessfulBuild/artifact/build/libs/IguanaTinkerTweaks-1.7.10-2.1.5.149.jar

**Comment by LegendLength** [comment]
Thank you TW looks great
