### ISSUE TITLE
Gravisuit Vajra Tool have only Tin Level.

### ISSUE THREAD

**Issue by Dream-Master** [SlimeKnights/IguanaTweaksTConstruct#152]
The Gravisuite Addon Vajra have only Tin Level with Iguana Tweaks. This tool is a high Tier Item and have to have Level 9.
I try to change the value in the Tools config but it did not working.
Tested with Gravisuit 2.0.3 and Iguana Tinker Tweaks 2.1.5

http://forum.industrial-craft.net/index.php?page=Thread&threadID=6915

**Comment by bonii-xx** [comment]
#60

**Comment by Dream-Master** [comment]
Is there any way to blacklisting items/mods?. Because you crafting a expencive tool and you cant mine all things with it.
