### ISSUE TITLE
[SUGGESTION] Reload Command

### ISSUE THREAD

**Issue by Neodark7** [SlimeKnights/IguanaTweaksTConstruct#154]
Hi, Can you add a reload command to reload main/restrictions/overrides configs ? :)

**Comment by Gunner76th** [comment]
As this is a Forge mod and not a bukkit plugin, I doubt that would be possible. With the exception of a very few forge mods, once a client/server is loaded it is unable to apply changes made to configs. 

Also, with servers/clients running Forge, making changes to your configs while the server/client is running is strongly discouraged. Doing so has been known on rare occasions to cause world corruptions. Unless you are running over 200 mods, the time it takes to shutdown a server, hit save in your text editor, and then restart your server (even over a shitty internet connection via SSH) is minimal.

**Comment by Neodark7** [comment]
@Gunner76th "10 Jul 2015" :D
