### ISSUE TITLE
Mattock gains no XP when digging Sand/Gravel

### ISSUE THREAD

**Issue by cabrera** [SlimeKnights/IguanaTweaksTConstruct#157]
When using the Mattock (combination hoe, axe, shovel), I expect to gain XP when gathering (dirt, sand, gravel, clay, etc.).

Bug: no XP is acquired when gathering sand/gravel

Confirmed working as expected - Mattock gains XP when:

* Cutting lumber
* Gathering dirt/clay
* Hoeing

Versions:

* Minecraft: 1.7.10
* IguanaTweaks: 2.1.5
* Tinker's Construct: 1.8.5

Thanks!

**Comment by bonii-xx** [comment]
Mattocks are not actually effective on sand and gravel, they therefore don't gain xp.
