### ISSUE TITLE
Unable to Repair in Crafting Grid

### ISSUE THREAD

**Issue by votex09** [SlimeKnights/IguanaTweaksTConstruct#159]
# Allows to repair your tool in a crafting grid, without tool station [default: true]

```
B:easyToolRepair=true
```

Yet, unable to do so.  Works in the Tool station.
ExtraTiC installed.
Erebus installed.
Tinkers' Modifiers NOT installed.

ITT acting strangely: Able to make stone tools and have them actually work.
    # Stone Tools can only be used to create casts, but no tools [default: true]
    B:disableStoneTools=true

Stone parts do not say "Can only be used in forging"

**Comment by votex09** [comment]
![stonetool](https://cloud.githubusercontent.com/assets/10671494/8763450/c42cb76e-2d61-11e5-905f-6e9a08be730b.PNG)

Unorganized Mod List as stated by LOG:
mcp, FML, Forge, appliedenergistics2-core, Aroma1997Core, CodeChickenCore, ivtoolkit, MobiusCore, NotEnoughItems, OpenComputers|Core, OpenEye, ThaumicTinkerer-preloader, OpenModsCore, <CoFH ASM>, Pistronics2, lucky, ArmorStatusHUD, DamageIndicatorsMod, ae2stuff, AncientWarfareAutomation, AncientWarfare, AncientWarfareNEIPlugin, AncientWarfareNpc, AncientWarfareStructure, aobd, AppleCore, appliedenergistics2, Aroma1997CoreHelper, Aroma1997sDimension, Artifacts, Artifice, asielib, asietweaks, Automagy, Backpack, bdlib, BiblioCraft, BiblioWoodsBoP, BiblioWoodsForestry, BiblioWoodsNatura, BigReactors, bigtrees, Botany, BinnieCore, ExtraBees, ExtraTrees, Genetics, BiomesOPlenty, AWWayofTime, Botania, BuildCraft|Energy, BuildCraft|Factory, BuildCraft|Transport, BuildCraft|Builders, BuildCraft|Silicon, BuildCraft|Robotics, BuildCraft|Core, BuildCraft|Compat, bcadditions, CarpentersBlocks, ChickenChunks, chisel, ChiselFacades, chiseltones, CoFHCore, CompactMachines, ComputerCraft, computronics, CosmeticArmor, CraftHeraldry, menagerie, props, debug, denseores, DimensionalAnchors, DraconicEvolution, eplus, Enchiridion, Enchiridion2, endercompass, EnderIO, EnderStorage, EnderZoo, eureka, extracells, ExtraTiC, ExtraUtilities, FastCraft, Steamcraft, FloodLights, fluxedcrystals, ForbiddenMagic, Forestry, fossil, ganysend, ganysnether, ganyssurface, GardenContainers, GardenCore, GardenStuff, GardenTrees, gendustry, advgenerators, GregsLighting, guideapi, HardcoreEnderExpansion, IguanaTweaksTConstruct, ImmersiveEngineering, ImmibisCore, ImmibisPeripherals, InfernalMobs, InGameInfoXML, InGameInfoXML|AWWayofTimeIntegration, InGameInfoXML|simplyjetpacksIntegration, InGameInfoXML|terrafirmacraftIntegration, InGameInfoXML|ThaumcraftIntegration, inpure|core, inventorytweaks, iridiummod, IronChest, JABBA, koresample, LogisticsPipes, LunatriusCore, MagicBees, Magistics, malisiscore, malisisdoors, Mantle, Mekanism, MekanismGenerators, MekanismTools, Metallurgy, MetallurgyCore, MineFactoryReloaded, MineFactoryReloaded|CompatAppliedEnergistics, MineFactoryReloaded|CompatAtum, MineFactoryReloaded|CompatBackTools, MineFactoryReloaded|CompatBuildCraft, MineFactoryReloaded|CompatChococraft, MineFactoryReloaded|CompatExtraBiomes, MineFactoryReloaded|CompatForestry, MineFactoryReloaded|CompatForgeMicroblock, MineFactoryReloaded|CompatIC2, MineFactoryReloaded|CompatMystcraft, MineFactoryReloaded|CompatProjRed, MineFactoryReloaded|CompatRailcraft, MineFactoryReloaded|CompatSufficientBiomes, MineFactoryReloaded|CompatThaumcraft, MineFactoryReloaded|CompatThermalExpansion, MineFactoryReloaded|CompatTConstruct, MineFactoryReloaded|CompatTwilightForest, MineFactoryReloaded|CompatVanilla, MineTweaker3, modtweaker2, morechisels, MouseTweaks, Natura, NaturalAbsorption, NEIAddons, NEIAddons|AppEng, NEIAddons|Botany, NEIAddons|Forestry, NEIAddons|CraftingTables, NEIAddons|ExNihilo, neiintegration, NetherOres, notenoughkeys, neresources, OpenBlocks, OpenComputers, OpenMods, OpenPeripheral, OpenPeripheralCore, OpenPeripheralIntegration, MapWriter, Opis, fodc, harvestthenether, harvestcraft, pressure, ProjectBlue, ProjRed|Core, ProjRed|Compatibility, ProjRed|Integration, ProjRed|Transmission, ProjRed|Illumination, ProjRed|Expansion, ProjRed|Transportation, ProjRed|Exploration, quiverchevsky, quivermobchevsky, Railcraft, RandomThings, reccomplex, RArm, RedstoneArsenal, RedstonePasteMod, RefinedRelocation, xreliquary, rftools, RouterReborn, Sanguimancy, scottstweaks, simplyjetpacks, statues, StevesAddons, StevesCarts, StevesFactoryManager, StevesWorkshop, supercraftingframe, tcnodetracker, TConstruct, technom, Thaumcraft, thaumcraftneiplugin, thaumicenergistics, ThaumicTinkerer, erebus, ThermalDynamics, ThermalExpansion, ThermalFoundation, recycling, ThermalSmeltery, TMechworks, Translocator, ttCore, TwilightForest, Waila, WailaHarvestability, wailaplugins, wawla, weaponmod, witchery, WR-CBE|Core, WR-CBE|Addons, WR-CBE|Logic, Ztones, bspkrsCore, Baubles, ForgeMicroblock, ForgeMultipart, McMultipart, libsandstone, MrTJPCoreMod

**Comment by RareDevil** [comment]
Seems like this is the same problem that i have. I have google to the end of the universe and back and the only thing i seem to be able to find out that this may be a problem with Extra TiC. But i cant find out if developer of Extra TiC knows about this. But just to make sure this is same problem that i have please try to remove Extra TiC and see if the problem is still there.
