### ISSUE TITLE
Dirty Cheater Config Suggestion

### ISSUE THREAD

**Issue by CPWMA** [SlimeKnights/IguanaTweaksTConstruct#160]
While I understand you dislike the exp cheat with MmmMmmMmmMmm, I do believe it's a bit uncool of you to make this option not be able to be turned off. As the players of the mod we should be allowed to play however we like if we choose too, even if it involves so called dirty cheating. So maybe some sort of config option to remove it or maybe at least get rid of the cheat in a nicer manner than the chicken method maybe making it so the test dummy does not make exp at all somehow. PS: Even for non-cheating players who work hard to build a mob farm they cannot use it appropriately to level due to this fix.

**Comment by bonii-xx** [comment]
That's why there is a command to level up your tool if you want to cheat. :P
It doesn't affect anybody who kills things the regular way.

**Comment by CPWMA** [comment]
That's not the point of the matter say we don't want to use commands for cheating and rather feel like the grind on the dummy is a better way for it, even if that wasn't our belief we, we being me and some friends, don't feel the need to op everyone that happens to be on our server or to constantly give their weapon a level so I bring up the question again why not just add a config option for the dummy cheat?

**Comment by bonii-xx** [comment]
Because I said no. ;o

**Comment by CPWMA** [comment]
That's like the worst thing, you don't even have an argument or some sort of reasoning behind your choice. I'm glad and all you picked up the mod but you really want to be this kind of person with it?

**Comment by CPWMA** [comment]
Also maybe the effect shouldn't be caused by dead entities because it doesn't allow fast killing of mobs in a mob grinder especially since the effect doesn't take place till the end of the level. I'm trying to compromise with you since you work hard on the mobs but you are being fairly rude with this whole dirty cheater thing.
