### ISSUE TITLE
Haste modifier acting strange

### ISSUE THREAD

**Issue by PrettyHeatToast** [SlimeKnights/IguanaTweaksTConstruct#165]
After replacing a part of a tool with haste thos happens.
![](http://media-elerium.cursecdn.com/attachments/25/793/635754877274784212.png)

**Comment by UnderMybrella** [comment]
That's almost certainly a bug with Tinkers' Modifiers; either remove the secondary redstone/haste modifier you have or add a piece of redstone to the items that modifier has.
