### ISSUE TITLE
[Mod Suggestion]; Specify Block Minings Levels

### ISSUE THREAD

**Issue by Lanse505** [SlimeKnights/IguanaTweaksTConstruct#172]
Hello!

This might sound like a strange request and I'm not sure if it's possible already through the existing configs but The ability to add blocks through the configs to specific mining levels (to for example fix certain ores mining levels and such). This would help out a bunch with certain mod packs who focus on mining progression as a specific feature of the pack :)

**Comment by bonii-xx** [comment]
See forum post.
