### ISSUE TITLE
[Mod Suggestion]: Harvest Level Tweaking Through Configs

### ISSUE THREAD

**Issue by Lanse505** [SlimeKnights/IguanaTweaksTConstruct#173]
Hello!

Just as the titel reads I'd suggest adding the ability to tweak certain aspects of Tool parts through the configs such as Harvest Levels, Possible Aspects of Material Types depending on part. 

If this is already possible then please just call me silly and give tell me how to >-<''' I need to learn this stuff and I can't find any good info about it ^^'.

**Comment by bonii-xx** [comment]
See forum post.
