### ISSUE TITLE
[Feature Request] A way to disable a modifier, for example the Flux Capacitor Modifier

### ISSUE THREAD

**Issue by ExDomino** [SlimeKnights/IguanaTweaksTConstruct#174]
I would like to find an way to disable the flux capacitor modifier from TinkerConstruct, but there is no option in the main mod to do so. Is there a way with IguanaTinkerTweaks to do so please? My need is to remove the ability to add this modifier in the tool forge. Thanks in advance!

**Comment by bonii-xx** [comment]
http://minecraft.curseforge.com/mc-mods/224971-tinkers-modifiers

**Comment by ExDomino** [comment]
Thanks! ^^
