### ISSUE TITLE
replacing tool part not changing its modification

### ISSUE THREAD

**Issue by killmetohell** [SlimeKnights/IguanaTweaksTConstruct#175]
On Extra Utilities i have bug where if i would replace one tool part with its one of own it doesn't apply its modifier. I don't if its same with thermal foundation because i only tried one of it material to placed it with had it said it had writable and nothing happen with it modifier.

**Comment by bonii-xx** [comment]
Only vanilla tcon materials are supported.

**Comment by killmetohell** [comment]
oh
