### ISSUE TITLE
Restrictions.cfg Not restricting some parts listed.

### ISSUE THREAD

**Issue by Dominance** [SlimeKnights/IguanaTweaksTConstruct#183]
As you can see here http://pastebin.com/ji9ZTXnD No hammers should be able to be crafted. Yet you can still craft them. Logs to correspond to this issue. http://pastebin.com/GUyy7U2T Not sure if this is on my end or something else.

**Comment by bonii-xx** [comment]
># The allowed and restricted entries are (=should be) equal. They're just both there for visibility.
You can only use one of the two, you can't mix and match. Also Obsidian hammerhead is in both.

**Comment by bonii-xx** [comment]
The error in the log seems to be caused by a broken material. Either a consequence of the above or another mods fault I'd say.
