### ISSUE TITLE
Minecraft crashing when trying to modify tinkers tools

### ISSUE THREAD

**Issue by EMan666** [SlimeKnights/IguanaTweaksTConstruct#197]
Whenever i try to replace parts on my tools the game crashes. I'm running the latest version of both ITT and TiCo.

Forge Version: 10.13.4.1492
ITT :  2.1.5
TiCo: 1.8.8

[crash-2014-08-24_21.50.40-client.txt](https://github.com/SlimeKnights/IguanaTweaksTConstruct/files/46185/crash-2014-08-24_21.50.40-client.txt)

**Comment by mightydanp** [comment]
Minecraft Forge 10.13.0.1207>
CodeChickenCore{1.0.2.9}
NotEnoughItems{1.0.2.15}
inventorytweaks{1.58-147-645ca10}
voxelmap{1.7.10} [VoxelMap No Radar] (Zans-MinimapNoRadar-Mod-1.7.10.jar) 

i do not see any thing that says iguana tweaks was loaded in you crash log

**Comment by bonii-xx** [comment]
Nor TConstruct, for that matter.

**Comment by EMan666** [comment]
That's weird because i'm know i'm using both because i have all the crafting items and the tools and i know i have Iguana Tweaks because i was in the config file uping the max level of tools.
