### ISSUE TITLE
Iguanas Not Registering Some TE Metals

### ISSUE THREAD

**Issue by LouieK22** [SlimeKnights/IguanaTweaksTConstruct#198]
In an a modified version of Sky Factory 2. I am unable to make Signalium, Enderium, ect. tools.
I am unsure if this is a config issue or what. I saw nothing in the configs pertaining to this. Iguanas seamed to register all other metals in TE, except those made by alloys.

Config: https://app.box.com/s/mmhyag38bz3ca1sfidhv33vxy2augg8b

Would like some help, Thanks,
LouieK22

**Comment by bonii-xx** [comment]
Iguana tweaks doesn't add any materials. TE alloys are added by ExtraTiC.
