### ISSUE TITLE
Pick Boost XP penalty config not functioning properly

### ISSUE THREAD

**Issue by stoops420** [SlimeKnights/IguanaTweaksTConstruct#200]
I have my config set so that when a tool head is replaced 100% of the skill XP and 100% of the Mining level XP should be removed. However, when I build a pickaxe with a stone head (which doesnt ever raise in mining level btw) and then replace it with a Flint head, that flint head will never increase in mining level. Creating a brand new pick with a flint head works as expected.

Let me know if you need any more info than that.

**Comment by bonii-xx** [comment]
Working as intended. Flint is meant as the minimum starting point for a new pickaxe.
