### ISSUE TITLE
Mismatched Bowstring Recipe for Crossbow!?

### ISSUE THREAD

**Issue by ArkavianX** [SlimeKnights/IguanaTweaksTConstruct#206]
Cannot craft regular crossbow string in TConstruct Part Builder

There are 3 different bowstring models, one for stencil, basic bowstring then two colors of the special bowstring (reddish and bluish). There is no working recipe for the regular bowstring! 

(SkyFactory 2.4)

**Comment by bonii-xx** [comment]
Then the SkyFactory makers broke it or removed it.
