### ISSUE TITLE
Restrictions breaking new mod.

### ISSUE THREAD

**Issue by Chinthor** [SlimeKnights/IguanaTweaksTConstruct#219]
For the record, this is probably supposed to be handled by the mod author. I just need a quick fix for the time being.

I'm using the most recent versions of ITT, ExtraTic, and MatterOverdrive, Using MineTweaker/ModTweaker, I can reconcile the melting, crafting, and armor recipes. That is all good.

But somewhere along the line, Tritanium is removed as a valid material to cast parts.

Since this won't be addressed until his 1.8 update at the soonest, how can I disable all restrictions on casting? Trying to splice the Tritanium into the intersection of these mods is far beyond me, and I'm not disabling any materials anyway.

Thanks

**Comment by bonii-xx** [comment]
Disable the restrictions module in the (module) configs

**Comment by Chinthor** [comment]
Hai sensei. My eternal gratitude.
