### ISSUE TITLE
Skill XP not displaying

### ISSUE THREAD

**Issue by Redlotus99** [SlimeKnights/IguanaTweaksTConstruct#221]
I am running a 1.7.10 server and everything is working correctly. The only issue I am having is that the Skill XP is not showing on any of the tools. The tools do level up, but there is just no 0/1000xp visible.

Any ideas on what might cause this? 

Using:

Iguana's Tinkers Tweaks - 2.1.6
Minecraft - 1.7.10
Forge - 1614

**Comment by bonii-xx** [comment]
You disabled the tooltip in the configs.

**Comment by Redlotus99** [comment]
I have not touched the config for Iguana's everything is set to default.  I'll verify the client configs as well, but I know the server is default.

http://pastebin.com/SPW19yau
