### ISSUE TITLE
Pickaxes constructed in crafting grid cannot be boosted

### ISSUE THREAD

**Issue by theJ8910** [SlimeKnights/IguanaTweaksTConstruct#222]
This seems to be due to mining xp-related NBT data not being added to pickaxes when constructing tools in this way.

I'm using Iguana Tinkers' Tweaks 2.1.6 for Minecraft 1.7.10.

How to reproduce:
1. Set IguanaTinkerTweaks/main.cfg > tweaks > B:easyToolBuilding=true to enable crafting tools in a normal 2x2 or 3x3 crafting grid
2. Craft a wooden tool rod, wooden binding, and wooden pickaxe head
3. Place the parts in the player's 2x2 crafting grid and craft the pickaxe.
4. Hold SHIFT and hover over the pickaxe to open the tooltip, and note that there is no "Mining XP" entry beneath "Mining Level".

**Comment by bonii-xx** [comment]
You need at least a flint pick to get started. Everything before that is considered a starting tool and doesn't get xp.

**Comment by theJ8910** [comment]
Sorry! I forgot that was the case, it's been a while since I played. But there is a bug here that prevented me from boosting my pick. Try this instead:

First, craft a wooden pickaxe, then replace the head of the pickaxe with a flint head. The pickaxe should get Mining XP then, shouldn't it? But it doesn't: http://imgur.com/8HWwKHj

**Comment by bonii-xx** [comment]
It needs to be a freshly crafted pick, a starting pick stays a starting pick forever.
