### ISSUE TITLE
[Request] Option to rename tool levels

### ISSUE THREAD

**Issue by Shahelion** [SlimeKnights/IguanaTweaksTConstruct#225]
For 1.7.10 if possible. Heard that this was supposedly a thing, was a bit disappointed that it got dropped.

**Comment by KnightMiner** [comment]
1.7.10 development has stopped, though this is fully possible using a resource pack already

**Comment by Shahelion** [comment]
Is it? How would I go about doing so?

**Comment by bonii-xx** [comment]
Providing a resource pack that overwrites the localization entries for the mining levels. There are several modpacks out there who do that already. Best try google.
