### ISSUE TITLE
Permission for mod "reposting" on Chinese forums

### ISSUE THREAD

**Issue by Robijnvogel** [SlimeKnights/IguanaTweaksTConstruct#226]
Just wanted to inform you about [this](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2176855-iguanas-tinker-tweaks?comment=849).
I know this isn't exactly an issue, but I couldn't find a PM option on Github and I know this will be read.
Keep up the good work!

**Comment by Robijnvogel** [comment]
Thank you!

**Comment by bonii-xx** [comment]
Sure
