### ISSUE TITLE
Compatability with Avarita's Skullfire Sword

### ISSUE THREAD

**Issue by Whimsyturtle** [SlimeKnights/IguanaTweaksTConstruct#228]
I've had an Issue with Avarita's Skullfire Sword not working properly.
(https://github.com/SpitefulFox/Avaritia/issues/103)

> The issue occurs with only Avarita, Mantle, TConstruct, and IguanaTinkerTweaks installed.
> However, I've just figured out it's Iguana's MobHeads module, which is overriding all of the mob head  drops, and seems to be enabled in both modpacks I've used with both mods.
> In Iguana's Modules.cfg, the following clears it up:
> B:MobHeads=false 
> (Sent By TrypChangeling)

So would there be a way to make both mods compatible with each other without changing the config file?

Thanks

**Comment by bonii-xx** [comment]
I don't know what the skullfire sword does, but if it has anything to do with mob drops, then most likely not. Also I"m not developing for 1.7 anymore.

**Comment by Whimsyturtle** [comment]
Alright then. You want to close the issue?

**Comment by bonii-xx** [comment]
Yeah, let's close it. Looks cleaner ;)
