### ISSUE TITLE
Compatibility for Extra Food?

### ISSUE THREAD

**Issue by reddvilzz** [SlimeKnights/IguanaTweaksTConstruct#236]
I've posted the issue in , [ExtraFood github](https://github.com/TeamDmfMM/Extra-Food/issues/46#issuecomment-296881351) but I'm just wondering if the compatibility can also be applied here maybe?

Basically the issue is using clayBucket to scoop out water turned it into ironBucket filled with water instead of returning it back to clayBucket. In this case from ExtraFood it is Bucket of Sea Water.

Thank you.

**Comment by bonii-xx** [comment]
This mod is not being developed anymore.

**Comment by reddvilzz** [comment]
Oh okay thank you.
