### ISSUE TITLE
ToolOverride.cfg not working

### ISSUE THREAD

**Issue by Marty137** [SlimeKnights/IguanaTweaksTConstruct#57]
I am unable to change the default mining level of non-tcon and vanilla tools.  After generating the additional config files from doing:    
This module allows to override about any values relevant for TConstruct or IguanaTinkerTweaks. B:Override=true

No matter what I set in the ToolOverride.cfg, the tool still will only mine what is set in the ToolDefault.cfg.  I've even tried to edit the ToolDefault.cfg, which does nothing.

Just to make sure I'm not doing something wrong, here is my override config.
http://pastebin.com/rhKF7VFV

I'm not sure if it matters but I noticed the lack of capitalization in the configs, where NEI would show ItemPickThaumium, the config is all lowercase.

**Comment by bonii-xx** [comment]
Will have a talk with Azanor then.

**Comment by bonii-xx** [comment]
https://github.com/Azanor/thaumcraft/issues/1451
