### ISSUE TITLE
Can't understand how to change block requirements

### ISSUE THREAD

**Issue by earthcrafterman** [SlimeKnights/IguanaTweaksTConstruct#61]
I feel like a major noob, but no matter what I put in info, the harvest levels of blocks do not change. My config:

http://pastebin.com/ytAMW22W

**Comment by bonii-xx** [comment]
Well, you could start off by reading the huge comment at the top, and by throwing a look into the default-file to see how you're supposed to do it.

**Comment by earthcrafterman** [comment]
*FACEPALM*

Very sorry, I can't believe I didn't notice that... that's what I get for skimming.

**Comment by bonii-xx** [comment]
Got it working? :)

**Comment by earthcrafterman** [comment]
Just fixed the config, trying it out now

**Comment by earthcrafterman** [comment]
Um, the game just turned the config into the default override config...

**Comment by earthcrafterman** [comment]
This:
http://pastebin.com/7zetG1Lv

Turned into this:
http://pastebin.com/MjBq0SSN

When I booted up the game... I think I'm missing something T.T

**Comment by bonii-xx** [comment]
Because the game doesn't care about info. Info is for the user, not the game. :P

**Comment by bonii-xx** [comment]
Literally all you have to do is copy your stuff out of the defaults and adapt it.. that can't be too hard.

**Comment by earthcrafterman** [comment]
So if I'm understanding this right I should make it as so:
http://pastebin.com/daES697d

**Comment by bonii-xx** [comment]
Yes. It literally says so in the huge comment at the top. The very first thing.

**Comment by earthcrafterman** [comment]
I'm really sorry, but somehow even that didn't work, that exact file was overridden when I launched the game

**Comment by bonii-xx** [comment]
Do you have HarvestLevelTweaks disabled?

**Comment by earthcrafterman** [comment]
I implemented the config, and I can still break the blocks... :/

**Comment by bonii-xx** [comment]
If you have the HarvestLevelTweaks module disabled it wont work because of a bug. If it's enabled it should work just fine. If it doesn't work your config probably is broken.
This here worked perfectly fine for me: http://pastebin.com/ga4gvHzq

**Comment by earthcrafterman** [comment]
And even downloading the latest Zip won't fix it?

**Comment by earthcrafterman** [comment]
Yeah, I think my config is broken, any idea on how to fix it?

**Comment by bonii-xx** [comment]
There are no zips. Next release will fix it.
