### ISSUE TITLE
Bolts are behaving very strangely

### ISSUE THREAD

**Issue by squeek502** [SlimeKnights/IguanaTweaksTConstruct#62]
Here's what I did:

* Made a default TiC bolt with a manyullyn bolt core (without Iguanas Tinker Tweaks installed)
* Installed Iguana Tinkers Tweaks
* Put the manyullyn bolts in a crafting window to upgrade it to the Tweaks version

The result was Wooden Bolts with the Manyullyn Bolt and the Wooden Bolt switched (so that the wooden bolt is the Head)

It gets weirder.

If I then replace the bolt part with a different one in the Tool Forge, the replacement gets put in the Handle spot, and the Head always gets changed to Iron (Wooden Bolts + Copper Bolt (part) = Iron Bolts [with Iron Bolt head and Copper Bolt handle])

And to top it all off:

If I build a bolt when Iguanas Tinker Tweaks is installed, the bolt part gets put in the Handle position and the Head bolt is always Iron. Is that intended?

**Comment by bonii-xx** [comment]
Can't reproduce, working as intended for me. It either got fixed, or it's an edge case I guess.

![2015-01-01_19 22 54](https://cloud.githubusercontent.com/assets/722449/5592943/ad7c8916-91eb-11e4-94e5-acd6476186ba.png)
