### ISSUE TITLE
Inconsistent replacement of materials in override module.

### ISSUE THREAD

**Issue by talonos2** [SlimeKnights/IguanaTweaksTConstruct#67]
The override module replaces the "toolMaterials" field in TConsructRegistry, but not doesn't touch toolMaterialStrings. This means if you try to look up a tool material by string instead of by ID number, it returns the *old* material, prior to the modifications made by the override module.

If this is intentional, it should probably be more clearly documented. I was using the TConstructRegistry.getMaterial(string) method in a Mantle manual to display material information, and it was returning pre-replacement materials, which confused me to no end.

**Comment by bonii-xx** [comment]
You are correct, good sir.
