### ISSUE TITLE
Can't farm wither skull heads

### ISSUE THREAD

**Issue by Ephys** [SlimeKnights/IguanaTweaksTConstruct#70]
Because this fakeplayer check breaks every possible farm https://github.com/SlimeKnights/IguanaTweaksTConstruct/blob/0c0b978cc9bbe6ebe5b7a670d537929046285528/src/main/java/iguanaman/iguanatweakstconstruct/mobheads/handlers/MobHeadHandler.java#L46

If it's intended, can we have a config option to disable this please ?

**Comment by bonii-xx** [comment]
Hm, that might be true. I suppose you'll have to disable ITTs mobheads if you want to autofarm them.

**Comment by Ephys** [comment]
By moving the check at the top of the event, wither skulls would drop at a vanilla rate when farmed by fakeplayers. It would solve the problem but would also be inconsistent with the way the other heads drop (Just like vanilla I guess).

**Comment by bonii-xx** [comment]
Yes, but I don't want it changed. As I said you can always turn off the modheads to disable it, or you can increase the drop-rate for manual farming to compensate.

**Comment by Ephys** [comment]
Fair enough ! Well if there is nothing else to be said I guess we can close this issue ?
