### ISSUE TITLE
Massive lag in conjunction with Auto Packagers

### ISSUE THREAD

**Issue by devryb** [SlimeKnights/IguanaTweaksTConstruct#73]
I have tested this issue in Forge 1277 in the SkyFactory 2.2.3 modpack and is 100% repeatable.

Steps to reproduce:
Setup an auto sieve exporting to a chest with enderio conduits (Add 64x speed upgrades for testing purposes)
Place a hopper on the auto sieve so that gravel is continuously fed to the sieve
Place an autopackager beside the chest and another chest beside that
Run power to both the auto sieve and autopackager
For testing purpose spawn in about 15 stacks of flint and put it in the first chest
Now let the system run and open the first chest
Sort the inventory in the chest so that the flint is first before the broken ore from ex nihilo

You will receive massive lag from this setup, below are screenshots of the setup and profiling results from the issue and why I have logged this here instead of the autopackager bug reports

Profiling Result: http://puu.sh/eVCIr/5879bb08fa.png

Setup: http://puu.sh/eVE2d/f2e515e374.jpg
First chest contents: http://puu.sh/eVDY7/0ea3989f28.jpg

**Comment by bonii-xx** [comment]
Disable tool building in crafting grids in the configs. That can't be prevented due to the nature of tool crafting.

**Comment by devryb** [comment]
Hi, thanks for the response.

Just to confirm it's these two options?

    # Allows to create Tool Station Tools (2-3 Parts) in any crafting grid [default: false]
    B:easyToolBuilding=true

    # Allows to also create Tool Forge Tools (4 Parts) in any crafting grid [default: false]
    B:easyToolBuildingForge=true

**Comment by bonii-xx** [comment]
Yes, these two. I'll see that I can reduce the impact in the next version, but I can't completely eliminate it without killing sticks/bones and other materials as handles.
