### ISSUE TITLE
(Suggestion) Have help window tell why this part cannot be Created/Replaced/etc.

### ISSUE THREAD

**Issue by Proaxel** [SlimeKnights/IguanaTweaksTConstruct#74]
I'm currently playing through ME^4 and there have been several times where I try to replace a tool part, or create a part in the part builder with an incompatible material. What results is often total confusion because, well, it doesn't show why you can't do it. 

You first place the tool/pattern, and then the part you want to replace/create, but then nothing happens. You want to know why nothing is happening, but unfortunately you can't, because it doesn't tell you! 

So I suggest just a little thing to make life a bit easier. When something of the above or similar happens, have it show in the help window on the right describing why. 
Maybe some little messages like: 
-Cannot Create Part: Paper is not compatible with this stencil.
-Cannot Replace Part: Tool must be fully repaired first.
-Cannot Add Modifier: No modifier slots remaining.

(Maybe do something a bit similar with smeltery casting as well, except with a chat message?)

Just a little Quality-of-Life suggestion!

**Comment by squeek502** [comment]
Related: https://github.com/SlimeKnights/TinkersConstruct/issues/1320

**Comment by bonii-xx** [comment]
Gonna close this to prevent confusion since it's actually the same thing as squeeks behind the scenes.

**Comment by Proaxel** [comment]
I just saw that post awhile ago and I totally forgot about it somehow. Well that was my derp of the day.
