### ISSUE TITLE
Modifiers For Weapons Not Working.

### ISSUE THREAD

**Issue by Hlvv** [SlimeKnights/IguanaTweaksTConstruct#77]
Hi I am loving the changes you have made to this mod and would like to thank you, but there is a problem I am having with the modifier bonuses upon a weapon leveling up for the attack modifier.

I turned off all the modifiers besides the AllowAttack and AllowLuck/Fortune and everytime the weapon levels up it will not get the Attack modifier. I have tested it on all the weapons for the original Tinkers Weapons and the modifiers that do get applied to them with the configuration I have are...

1:Fortune
2:autosmelt
3:diamond
4:emerald
5:repair

Does not matter what weapon I use it gets these modifiers applied to it in the exact order every time. 

Thankfully the only other weapon I experimented with, the ninja star/shurikan does not have this problem. The Attack modifier gets applied with no problem.

I think the problem is that the original weapons are not registering the attack modifier as an appliable modifier. 

I am running the current IgTwTiCo, 1.7.10-2.1.2 

Thanks again.

**Comment by bonii-xx** [comment]
Should be fixed with b6b446587687efeffa12effaa28d00dea6696d64
