### ISSUE TITLE
Flint and Stone tools only have a mining level of stone

### ISSUE THREAD

**Issue by Numba90** [SlimeKnights/IguanaTweaksTConstruct#78]
As the title would suggest, flint and stone tools only have a mining level of stone. In the part builder it says copper, but tooltips of the part and the tool once constructed say stone, not copper. As such I can't mine anything except coal, stone... and stone...

**Comment by Numba90** [comment]
False alarm, I didn't pay attention to the configs enough. *sigh*

**Comment by bonii-xx** [comment]
You have no idea how often I've heard that before. ;D
