### ISSUE TITLE
Flint replacement interaction with autosmelt

### ISSUE THREAD

**Issue by TTFTCUTS** [SlimeKnights/IguanaTweaksTConstruct#79]
Autosmelt does not affect the gravel which replaces flint drops. If you have a mod installed such as chisel which adds a smelting recipe taking gravel, if you mine gravel and flint would have dropped, you get gravel instead of the result of smelting it.

The case for this being what happens is reinforced by fortune. As my pick gained levels in fortune, I got less and less concrete and more and more gravel, to the point at fortune 3 that I now get all gravel and no concrete, in line with the 100% flint drop rate for fortune 3 in vanilla.

**Comment by bonii-xx** [comment]
Meh. Autosmelt circumvents all events, that's why. However hammers don't autosmelt gravel anymore now, so it shoudln't be such a pain anymore. :D
