### ISSUE TITLE
Cannot pull out fixed tool in crafting window on server

### ISSUE THREAD

**Issue by bountyhog** [SlimeKnights/IguanaTweaksTConstruct#80]
This is a game-breaking glitch that means whenever I craft (in particular) broadswords and pickaxes, the data comes out wrong and of course the mod recognises it. However, when I try to pull out the fixed tool, I can't. On a sword it doesn't really matter (at least for now) since the only thing affected is damage, but my pickaxes are all only able to mine a level lower than they should be able to. My iron pickaxe couldn't mine tin despite being levelled, and my Manyullyn pick is stuck at Obsidian after being levelled. For the first few days playing this didn't happen but now that it's started to happen I can no longer play on the server. Nobody else seems to have reported the problem.

The version being run is 2.1.2, with Tinkers' 1.8.2a.

**Comment by bonii-xx** [comment]
Sync your configs with the server.
