### ISSUE TITLE
Unable to add flux capacitor

### ISSUE THREAD

**Issue by lokkenpa** [SlimeKnights/IguanaTweaksTConstruct#81]
I am unable to add one no matter the lvl of the capacitor to a full repaired pickaxe.  TC, Iguana's, forge and all that are up to date (not getting a reminder for updated versions when starting).  Been able to add one to a hammer.  I have all the requisite slots needed.

Cobalt is expensive (locating and risk/reward).

Phil

**Comment by bonii-xx** [comment]
Capacitor too big for your durability.
