### ISSUE TITLE
Random bonuses dont work properly

### ISSUE THREAD

**Issue by Creysys** [SlimeKnights/IguanaTweaksTConstruct#83]
I deactivated every random bonus but luck, redstone and quartz and i keep getting auto-smelt and other boni on my sword.

**Comment by bonii-xx** [comment]
Sounds like you enabled CompletelyRandomBonuses.

**Comment by Creysys** [comment]
I did not.

And even if i did auto-smelt is disabled.

I think the problem is because i only let quartz and lapis on a sword and the sword was already full of that it just applies a random bonus.

I dont know what you would think of it but id appreciate a config where i could enable getting a modifier instead of a random bonus if applied a random bonus failed.

**Comment by bonii-xx** [comment]
Well, show me your configs.

**Comment by Creysys** [comment]
http://pastebin.com/KigTmPx2

I already changed it. I had B:RandomBonuses=false set to true.
