### ISSUE TITLE
Mattock crash when leveling in Farming station

### ISSUE THREAD

**Issue by Zaflis** [SlimeKnights/IguanaTweaksTConstruct#84]
I made a mattock fully of manuyllum to use in EnderIO farming station, but then server suddenly crashed and keeps crashing when i try to restart it (because it's chunkloaded). Crashlog mentions words: levelUpTool and TileFarmStation, so i assume this is no hard guess on why :p  Propably tries to do something to player, but there is no such thing present.

Server crashlog: http://pastebin.com/EB97U73y

Possible workaround for me is maybe using MCEdit to remove the farming station. But it's my only way to autoharvest ghast seeds from magical crops. I don't know what i could edit from config to make it work.

Also if this is crashing, then there's reason to suspect tool leveling in autonomous activator has potential to crash too.

**Comment by bonii-xx** [comment]
https://github.com/CrazyPants/EnderIO/commit/471f6653514270ebbc02a334b19b68e67c54b690
