### ISSUE TITLE
Crash on use of part-replaced tool

### ISSUE THREAD

**Issue by Rodg88** [SlimeKnights/IguanaTweaksTConstruct#86]
Tested with build 109 and 110, I spawn in a new wooden lumber axe, replace the head and plate with flint parts, and start breaking the base of a vanilla oak. Crashes when it would normally just cut down the tree. Doesn't crash when I don't replace any of the parts.
http://pastebin.com/cqTDRepf

config for tool leveling:
toolleveling {
    # Adds a random bonus on these levelups if 'RandomBonuses' is enabled
    I:BonusesAtLevels <
        2
        4
        6
        8
     >

    # Each modifier is equally likely on levelup. Disables useful bonuses. [default: false]
    B:CompletelyRandomBonuses=false

    # The amount of modifiers new tools have. [range: 0 ~ 9, default: 0]
    I:ExtraModifiers=1

    # Adds an extra modifier on these levelups if 'ExtraModifiers' is enabled
    I:ModifiersAtLevels <
        3
        5
        7
        9
     >

    # Gives a random bonus every level, if false and levelling is on modifiers are given at levels 2 and 4 (requires 'toolLeveling=true') [default: true]
    B:RandomBonuses=true

    # Disables less-useful modifiers on levelups. Like a sword with silktouch, or a pickaxe with beheading. [default: true]
    B:UsefulBonuses=true

    # XP tooltip shows numbers, in addition to percentage [default: true]
    B:detailedXpTooltip=true

    #  [range: 1 ~ 99, default: 6]
    I:maxToolLevel=9

    # If true, only the heads of tools are examined when determining how much XP it takes to level up. (This only matters if you manually specify that some material types level faster than others using the override module) [default: true]
    B:onlyHeadsChangeXPRequirement=true

    # Current XP% is shown after the level [default: false]
    B:showMinimalTooltipXP=false

    # Current XP is shown when hovering over a tool [default: true]
    B:showTooltipXP=true

    # Can your skill with tools 'level up' as you use them? [default: true]
    B:toolLeveling=true

    # Exponential multiplier for required boost xp per level [range: 1.0 ~ 9.99, default: 1.12]
    S:xpPerBoostLevelMultiplier=1.12

    # Exponential multiplier for required xp per level [range: 1.0 ~ 9.99, default: 1.15]
    S:xpPerLevelMultiplier=1.15

    # Change the XP required to level up tools in % (higher = more xp needed) [range: 1 ~ 999, default: 100]
    I:xpRequiredToolsPercentage=100

    # Change the XP required to level up weapons in % (higher = more xp needed) [range: 1 ~ 999, default: 100]
    I:xpRequiredWeaponsPercentage=100
}

**Comment by Rodg88** [comment]
Actually, it just crashed again with freshly spawned in bone and iron lumber axes too, so maybe not to do with part replacing... The wooden lumber axe without part replacements doesn't crash, but also doesn't gain experience points after use.

**Comment by bonii-xx** [comment]
Incompatible tcon version.
