### ISSUE TITLE
Microblock Saw Item Icon

### ISSUE THREAD

**Issue by wiiv** [SlimeKnights/IguanaTweaksTConstruct#87]
I made icons for the microblock saws and they are now a config option. I can provide icons for this mod too.

**Comment by bonii-xx** [comment]
What icons are you talking about?

**Comment by wiiv** [comment]
The Ardite, Cobalt and Manyullyn microblock saws have models.
I made icons for them.

Check this closed issue in forge multipart:

https://github.com/Chicken-Bones/ForgeMultipart/issues/299

**Comment by wiiv** [comment]
Anyway, I've done them, they're here if you want to use them!

cobalt saw:
http://imgur.com/pU5Tj0E,Jh7EtIw,yCuU5J0#1

ardite saw:
http://imgur.com/pU5Tj0E,Jh7EtIw,yCuU5J0#0

manyullyn saw:
http://imgur.com/pU5Tj0E,Jh7EtIw,yCuU5J0#2

**Comment by wiiv** [comment]
Awesome!
