### ISSUE TITLE
A lot of smam in the console while MC is loading

### ISSUE THREAD

**Issue by crunkazcanbe** [SlimeKnights/IguanaTweaksTConstruct#88]
As the title says . There is quit a bit of console spam , and I don't know if this is OK , and/or to ignore it .

http://pastebin.com/ZTrLpGDs

Thanx -Crunk

**Comment by bonii-xx** [comment]
Hm, might happen if you don't have NEI.

**Comment by crunkazcanbe** [comment]
Yep installing NEI fixed this issue . Sorry to have bothered !

Thank you!

-Crunk

**Comment by bonii-xx** [comment]
It's ok, it was missing a check
