### ISSUE TITLE
Issue with adding new Mats to Patterns.

### ISSUE THREAD

**Issue by Drehverschluss** [SlimeKnights/IguanaTweaksTConstruct#89]
Hello sir.

I found a little issue in Iguawa.

I added new materials to some Patterns but they wont show in the Pattern as a valied matierial.
They working though. But when i am in the PartBuilder and place the Pattern and the Material i want in the slots i need to close and open the Partbuilder to see if its able to craft.

i added this in the restriction.cfg
        Wood:swordblade
        Wood:fullguard
        Wood:mediumguard
        Wood:largeguard

**Comment by bonii-xx** [comment]
Can't reproduce. See if you can reproduce it with only tinkers and ITT.

**Comment by Drehverschluss** [comment]
Omg "I AM SO STUPID"

I found the fix in annother issue post. 
I'm so sorry dude to bother you everytime when i make something wrong :/

I just needed to sync my Server config with client config.

I'm so sorry hope you can forgive me ;)

**Comment by bonii-xx** [comment]
You are forgiven, my son.
