### ISSUE TITLE
Tinker Tools do x2 damage (?)

### ISSUE THREAD

**Issue by PokeMaserJ** [SlimeKnights/IguanaTweaksTConstruct#91]
I made a Tinker Iron Cleaver (11 attack damage / 5.5 hearts) And it can one shot zombies without any Sharpness / Smite. Not sure if this is the mod causing it, or just vanilla Tinkers'

**Comment by UndeadZeratul** [comment]
Could you be referring to [this](https://github.com/SlimeKnights/TinkersConstruct/issues/1325) issue?

**Comment by PokeMaserJ** [comment]
Think that's the same as I have. I think I'll close this
