### ISSUE TITLE
Clay Water Bucket & Pam's Harvestcraft

### ISSUE THREAD

**Issue by erima** [SlimeKnights/IguanaTweaksTConstruct#92]
Clay Water Buckets don't work with Pam's HarvestCraft recipes. 

Examples: An iron bucket on the crafting table equals 4 fresh water buckets. A fresh water bucket (or an iron bucket of water) and a pot equals HC salt. 

Clay water buckets should provide the same, especially considering the limitations on iron from using IguanaTiC.

**Comment by squeek502** [comment]
Might be as simple as registering the clay water bucket as `listAllwater` oredict.
