### ISSUE TITLE
Crashing after passing 350 redstone on Crossbow

### ISSUE THREAD

**Issue by Teleclast** [SlimeKnights/IguanaTweaksTConstruct#93]
http://pastebin.com/Mde6AdQR

I'm using Infinity modpack (1.0.1, had many issues upgrading to 1.0.2)
TiCo 1.7.10-1.8.2a
Iguana 1.7.10-2.1.2

Was upgrading crossbow, using current version of IguanaTweaks, was originally using ME^4's config fo it, but tried reverting back to no difference. Every time I view the crossbow (stuck inside the tool station). I've yet to try just breaking the tool station since it seems to break upon seeing that item.

e: I made sure that both the server and the client have the same configs, both when using the ones taken from ME^4 as well as when using the default ones.

**Comment by bonii-xx** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues/1369
