### ISSUE TITLE
Cannot pull out fixed tool in crafting window on server

### ISSUE THREAD

**Issue by GRedfox** [SlimeKnights/IguanaTweaksTConstruct#94]
I know this has already been asked and answered, however I don't know how to sync configs with the minecraft server (its a dedicated host we are paying for) if you could give me an explanation as to how that would be awesome thanks!

**Comment by bonii-xx** [comment]
Make sure the stuff in the configs folder is the same for your client and the dedicated server. I can't tell you how to run your server, ask your hoster.

**Comment by Teleclast** [comment]
Oddly enough, breaking the table and having it drop on the floor does not crash, and usually going into it a second time to add the same mods works, at least it did for me the three times I've run into this problem already on my server, which is 100% using the same for configs as the client.
