### ISSUE TITLE
Using latest DEV build Something wrong

### ISSUE THREAD

**Issue by crunkazcanbe** [SlimeKnights/IguanaTweaksTConstruct#95]
Like the title says I am using latest dev build IguanaTinkerTweaks-1.7.10-2.1.2.111 from 
https://dvs1.progwml6.com/jenkins/job/IguanaTConTweaks-1.7.10/ and latest DEV build of tinkers from https://dvs1.progwml6.com/jenkins/job/TConstruct_1.7.x/ Build TConstruct-1.7.10-1.8.2.build893 and I am getting this http://pastebin.com/nPvfTAc2 . Going back to TConstruct-1.7.10-1.8.2.build892 fixes this error with 0 errors in the console .

Thank you!

-Crunk

**Comment by bonii-xx** [comment]
Yes, the moving around of oredicting caused that. because it wasn't cleaned up when it got split, it seems.

**Comment by crunkazcanbe** [comment]
Thank you man very much!    :)

-Crunk
