### ISSUE TITLE
Mob head will not apply to pickaxe which started as wood, then changed to flint.

### ISSUE THREAD

**Issue by MinoForge** [SlimeKnights/IguanaTweaksTConstruct#97]
So I had a wooden(rod, bind, head) pickaxe to begin with. Eventually upgraded to flint head. Attempted to add a mob head(creeper) to it, to boost  the mining level. It would not apply. I didn't get the option of pulling it out of the tool forge, or tinkers' table.
I made a new pickaxe (bone rod, bone binding, and a flint head). Mob head applies just fine in the tool forge. 
I found this solution from someone who posted in the minecraftforum with the same issue, but seeing as it still isn't fixed, I assume you didn't see it and that I should report it here. Here is the thread, in case his information helps more than mine.
http://www.minecraftforum.net/forums/search?search-thread-id=2176855&search-forum-id=&forum-scope=f&display-type=0&search=mob+head&search-type=2&by-author=&begin-date=&begin-time=&end-date=&end-time=&min-posts=&min-views=&display-type=0&submit=y

**Comment by bonii-xx** [comment]
Show me the tool where it didn't work

**Comment by MinoForge** [comment]
As in... a picture? 
http://imgur.com/a/0DByG

**Comment by bonii-xx** [comment]
You tool doesn't have the ability to level up the mining level, so you also can't add a head. Did you change the configs somewhere in between?

**Comment by MinoForge** [comment]
I did not... I dunno. If no one else has the bug, then I'll assume that I done screwed something up. I wouldn't put it past me.



On Sunday, March 1, 2015 5:13 AM, boni <notifications@github.com> wrote:
 


You tool doesn't have the ability to level up the mining level, so you also can't add a head. Did you change the configs somewhere in between?
