### ISSUE TITLE
Crashing on tool part replacement

### ISSUE THREAD

**Issue by Magiks21** [SlimeKnights/IguanaTweaksTConstruct#98]
Setting up some mods for myself and some buddies. Trying to figure it all out and boil down the mod list and would rather keep TiC, Extra Tic, IguanaTeaks and Metallurgy 4.

Here is the crashlog: http://pastebin.com/7NKVfJ8g

If there is any support you can provide me with I would be immensely grateful!

**Comment by bonii-xx** [comment]
Curious. What materials?

**Comment by Magiks21** [comment]
Just got the information in from my guy testing it.

We have MFR installed as well.

When attempting to replace the bow limbs on a constructed Long Bow with MFR Pink Slime Bow Limbs, Client crashes.

When attempting to craft arrows with any tool rod other than one provided by either Tinkers or Vanilla, the client crashes as well.

I could go ahead and generate crash logs for a few different ones to get you a wider base if you'd like.

**Comment by bonii-xx** [comment]
You can't really craft arrows with tool rods. Show me one of those crashlogs please.

**Comment by Magiks21** [comment]
Here is for the tool rod when creating an arrow. Look like its the rendering of the arrow.
http://pastebin.com/TkCJiSXk

Here is for the Bow Limb being replaced.
http://pastebin.com/pM1DtkYq

**Comment by bonii-xx** [comment]
Either I already fixed the cause or some other mod messes with it. Can't reproduce it at all. You might want to try the latest dev builds to confirm.

**Comment by Magiks21** [comment]
I believe this might actually be an issue with Extra TiC.

Did a test to see if it may be another mod interfering. It is crashing with just TiC, Metallurgy and ExtraTiC installed. I will try to get in touch with Glassmaker.

Thanks for bearing with me bonii!
