### ISSUE TITLE
there was originally a plan to have silky cloth remove modifiers on tools any chance of geting this in now ?

### ISSUE THREAD

**Issue by kurokuno** [SlimeKnights/IguanaTweaksTConstruct#99]
i know the original one had plans to add this in cases where say you get fire on a sword making it more or less useless vs endermen and really bad if you have "special Ai" installed as a burning creeper will instantly explode

example: it would remove the last modifier added to a sword but not the last level forever removing that random modifier "stopping" people from just constantly farming the perfect sword?

**Comment by bonii-xx** [comment]
No.

**Comment by kurokuno** [comment]
Daww okie guess i will just have to config it to be a non random modifier then =P ty for at least taking a look bonii

**Comment by bonii-xx** [comment]
Np. Also the silky cloth would have removed ALL modifiers from the tool. Just removing a single one or the last one is in general impossible
